packets2: Add register and subscribe-related packets
energomonitor/bisquitt pull request #58
Opened 2022-10-24 10:14 UTC by mprymek

PR adds register and subscribe-related packets: `Register`, `Regack`, `Subscribe`, `Suback`, `Unsubscribe`, `Unsuback`.

Failed tests are OK. They will pass as long as all packets are merged in.

2022-11-09 09:15 UTC, dmajda requested changes
Looks good overall, I have just two minor comments.

I have a more general question though: Handling of Topic Alias Type, Topic Alias, Topic Name and Topic Filter is done in multiple packets. The code dealing with packing, unpacking, computing packet length, and stringification is highly repetitive. Have you considered abstracting it a bit?

2022-11-10 13:22 UTC, mprymek commented on packets2/regack.go
> +}
ok

2022-11-15 18:24 UTC, dmajda reviewed
Changes look good. I’m still curious about the answer to my question [above](https://github.com/energomonitor/bisquitt/pull/58#pullrequestreview-1173557558):

> I have a more general question though: Handling of Topic Alias Type, Topic Alias, Topic Name and Topic Filter is done in multiple packets. The code dealing with packing, unpacking, computing packet length, and stringification is highly repetitive. Have you considered abstracting it a bit?

2022-11-16 08:16 UTC, mprymek commented
> Changes look good. I’m still curious about the answer to my question [above](https://github.com/energomonitor/bisquitt/pull/58#pullrequestreview-1173557558):
> 
> > I have a more general question though: Handling of Topic Alias Type, Topic Alias, Topic Name and Topic Filter is done in multiple packets. The code dealing with packing, unpacking, computing packet length, and stringification is highly repetitive. Have you considered abstracting it a bit?

You are right that handling of these properties is much more unified and sane in MQTT-SN v.2 than in v.1 (e.g. the "long" topic ID type has the same flag value as the registered topic ID type in v.1 [1]) and there's probably room for some abstraction. Nevertheless, there are some minor deviations in particular packets and I must carefully investigate if it's  worth it and the abstraction will not just complicate the code without much benefit.

I think it's out of scope of this PR. I made an issue [2] and will take a look later.

[1] https://github.com/energomonitor/bisquitt/blob/main/packets1/packets1.go#L44
[2] https://github.com/energomonitor/bisquitt/issues/64

2022-11-16 09:14 UTC, dmajda approved these changes

2022-11-16 09:15 UTC, merged